# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndLogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpInstruction',
        ),
    ]
